---
title: CC or SJP Case Creation flow
config:
  theme: base
  themeVariables:
    fontFamily: Helvetica, Arial, Calibri
    clusterBkg: '#FFFFF8'
    primaryColor: '#FFF'
    secondaryColor: '#FFFFF8'
  layout: dagre
  markdownAutoWrap: false
---
flowchart LR

  classDef external fill:#BBDEFB
  classDef internal fill:#C8E6C9
  classDef email fill:#FEFFD6
  classDef in-out fill:#EEE

  INI-0@{ img: "https://raw.githubusercontent.com/RichardColeHMCTS/Mermaid-SVG/f9e54f57e215dffd8e8de842f6124855321a1210/Custom%20CVG/off-page-connector-left.svg", label: "Previous Flow", pos: "b", h: 60, constraint: "on" }

  subgraph CCF[" "]
 
    direction LR      
        CMD-1["`**Command Issued**
              progression.command.create-prosecution-case`"]
        CMD-2["`**Command Issued**
              progression.command.process-matched-defendats`"]
        CMD-3["`**Command Issued**
              progression.command.update-matched-defendant`"]
        EVT-1["`**Event Raised**
              progression.event.prosecution-case-created`"]
        P-EVT-1["`**Event Raised**
              public.progression.prosecution-case-created`"]
        EVT-2["`**Event Raised**
              progression.event.defendant-partial-match-created`"]
        EVT-3["`**Event Raised**
              progression.event.master-defendant-id-update-v2`"]
        EVT-4["`**Event Raised**
              progression.event.master-defendant-id-update`"]
        EVT-5["`**Event Raised**
              progression.event.defendants-master-defendant-id-update`" ]
        EVT-6["`**Event Raised**
              public.progression.prosecution-case-created`"]
        QUS-1{"`**Defendant
              match
              ?**`"}
  end

    INI-0 --> CMD-1
    CMD-1 --> EVT-1
    EVT-1 --> CMD-2 & P-EVT-1
    CMD-2 -- for each matched defendant --> QUS-1
    QUS-1 -- partial match --> EVT-2
    QUS-1 -- full match --> EVT-3 & EVT-4
    EVT-3 -- for each matched defendant not matching master defendant ID --> CMD-3
    CMD-3 --> EVT-5
    EVT-3 --> EVT-6
    EVT-5 --> EVT-6
    EVT-4 -- for each matched defendant not matching master defendant ID --> EVT-6

%% Assign Classes
  class INI-0,INI-1,B-OUT-0,B-OUT-1,B-OUT-2,B-OUT-3 in-out
  class P-EVT-0,P-EVT-1,P-EVT-2,P-EVT-3,P-EVT-4,CLD-0 external
  class EVT-0,EVT-1,EVT-2,EVT-3,EVT-4,EVT-5,EVT-6,EVT-7 internal

  click INI-0 href "history.back()" "This will return to previous page"