---
title: CC or SJP Case Creation flow
config:
  theme: base
  themeVariables:
    fontFamily: Helvetica, Arial, Calibri
    clusterBkg: '#FFFFF8'
    primaryColor: '#FFF'
    secondaryColor: '#FFFFF8'
  layout: dagre
  markdownAutoWrap: false
---
flowchart LR
  CCF-INI-0@{ label: "<b style=\"font-size: 14pt\">Previous<br>Flow<b>" }
  subgraph CCF[" "]
 
    direction LR      
        CCF-CID-1@{ label: "<b style=\"font-size: 14pt\">Command Issued</b><br>progression.command.create-prosecution-case" }
        CCF-CID-2@{ label: "<b style=\"font-size: 14pt\">Command Issued</b><br>progression.command.process-matched-defendats" }
        CCF-CID-3@{ label: "<b style=\"font-size: 14pt\">Command Issued</b><br>progression.command.update-matched-defendant" }
        CCF-ERI-1@{ label: "<b style=\"font-size: 14pt\">Event Raised</b><br>progression.event.prosecution-case-created" }
        CCF-ERP-1@{ label: "<b style=\"font-size: 14pt\">Event Raised</b><br>public.progression.prosecution-case-created" }
        CCF-ERI-2@{ label: "<b style=\"font-size: 14pt\">Event Raised</b><br>progression.event.defendant-partial-match-created" }
        CCF-ERI-3@{ label: "<b style=\"font-size: 14pt\">Event Raised</b><br>progression.event.master-defendant-id-update-v2" }
        CCF-ERI-4@{ label: "<b style=\"font-size: 14pt\">Event Raised</b><br>progression.event.master-defendant-id-update" }
        CCF-ERI-5@{ label: "<b style=\"font-size: 14pt\">Event Raised</b><br>progression.event.defendants-master-defendant-id-update" }
        CCF-ERI-6@{ label: "<b style=\"font-size: 14pt\">Event Raised</b><br>public.progression.prosecution-case-created" }
        CCF-QUS-1{"<b>Defendant<br>match<br>?</b>"}
  end

    CCF-INI-0 --> CCF-CID-1
    CCF-CID-1 --> CCF-ERI-1
    CCF-ERI-1 --> CCF-CID-2 & CCF-ERP-1
    CCF-CID-2 -- for each matched defendant --> CCF-QUS-1
    CCF-QUS-1 -- partial match --> CCF-ERI-2
    CCF-QUS-1 -- full match --> CCF-ERI-3 & CCF-ERI-4
    CCF-ERI-3 -- for each matched defendant not matching master defendant ID --> CCF-CID-3
    CCF-CID-3 --> CCF-ERI-5
    CCF-ERI-3 --> CCF-ERI-6
    CCF-ERI-5 --> CCF-ERI-6
    CCF-ERI-4 -- for each matched defendant not matching master defendant ID --> CCF-ERI-6

    CCF-INI-0@{ shape: trap-t}
    CCF-CID-1@{ shape: rounded}
    CCF-CID-2@{ shape: rounded}
    CCF-CID-3@{ shape: rounded}
    CCF-ERI-1@{ shape: rounded}
    CCF-ERP-1@{ shape: rounded}
    CCF-ERI-2@{ shape: rounded}
    CCF-ERI-3@{ shape: rounded}
    CCF-ERI-4@{ shape: rounded}
    CCF-ERI-5@{ shape: rounded}
    CCF-ERI-6@{ shape: rounded}

    style CCF-INI-0 fill:#EEE
    style CCF-ERI-1 fill:#C8E6C9
    style CCF-ERI-2 fill:#C8E6C9
    style CCF-ERI-3 fill:#C8E6C9
    style CCF-ERI-4 fill:#C8E6C9
    style CCF-ERI-5 fill:#C8E6C9
    style CCF-ERI-6 fill:#BBDEFB
    style CCF-ERP-1 fill:#BBDEFB
    style CCF-QUS-1 fill:#FFE0B2